theme: jekyll-theme-hacker
title: DragonRuby Game Toolkit Resources
author: Flavio Salvador López Orellana
email: StardragonEX@gmail.com
description: This site has links to free and paid resources to learn DragonRuby Game Toolkit, Ruby, C, etc., everything related to DragonRuby Game Toolkit and to make games with it.
github_username: StardragonEX
show_excerpts: true
